// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"

	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// BaseEntity is an object. Contains shared properties for all the entities
type BaseEntity struct {
	// Id:
	Id string `json:"id" mapstructure:"id"`
	// Name:
	Name string `json:"name" mapstructure:"name"`
}

// NewBaseEntity instantiates a new BaseEntity with default values overriding them as follows:
// 1. Default values specified in the BaseEntity schema
// 2. Default values specified per BaseEntity property
func NewBaseEntity() *BaseEntity {
	m := &BaseEntity{}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for BaseEntity. It set the default values for the BaseEntity type
func (m *BaseEntity) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewBaseEntity()

	// Unmarshal using an alias to avoid an infinite loop
	type alias BaseEntity
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m BaseEntity) Validate() error {
	errors := validation.Errors{
		"id": validation.Validate(
			m.Id, validation.Required, is.UUID,
		),
	}
	return errors.Filter()
}

// GetId returns the Id property
func (m BaseEntity) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *BaseEntity) SetId(val string) {
	m.Id = val
}

// GetName returns the Name property
func (m BaseEntity) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *BaseEntity) SetName(val string) {
	m.Name = val
}
