// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Wrapper is an object.
type Wrapper struct {
	// NullableStringEnumWithNull: Add nullable in the prop for non nullable enum
	NullableStringEnumWithNull *StringEnumWithNull `json:"nullableStringEnumWithNull,omitempty" mapstructure:"nullableStringEnumWithNull,omitempty"`
	// NullableStringEnumWithNullAndZero: Add nullable in the prop for non nullable enum with zero value and null
	NullableStringEnumWithNullAndZero *StringEnumWithNullAndZero `json:"nullableStringEnumWithNullAndZero,omitempty" mapstructure:"nullableStringEnumWithNullAndZero,omitempty"`
	// NullableStringEnumWithZero: Add nullable in the prop for non nullable enum with zero value
	NullableStringEnumWithZero StringEnumWithZero `json:"nullableStringEnumWithZero,omitempty" mapstructure:"nullableStringEnumWithZero,omitempty"`
	// RequiredNullableStringEnumWithNull: Add nullable in the prop for non nullable enum
	RequiredNullableStringEnumWithNull *StringEnumWithNull `json:"requiredNullableStringEnumWithNull" mapstructure:"requiredNullableStringEnumWithNull"`
	// RequiredNullableStringEnumWithNullAndZero: Add nullable in the prop for non nullable enum with zero value and null
	RequiredNullableStringEnumWithNullAndZero *StringEnumWithNullAndZero `json:"requiredNullableStringEnumWithNullAndZero" mapstructure:"requiredNullableStringEnumWithNullAndZero"`
	// RequiredNullableStringEnumWithZero: Add nullable in the prop for non nullable enum with zero value
	RequiredNullableStringEnumWithZero StringEnumWithZero `json:"requiredNullableStringEnumWithZero" mapstructure:"requiredNullableStringEnumWithZero"`
	// RequiredStringEnum: a required regular string enum
	RequiredStringEnum StringEnum `json:"requiredStringEnum" mapstructure:"requiredStringEnum"`
	// RequiredStringEnumNullable: a required string enum that is nullable
	RequiredStringEnumNullable StringEnumNullable `json:"requiredStringEnumNullable" mapstructure:"requiredStringEnumNullable"`
	// RequiredStringEnumWithNull: Ref a non nullable enum. It should not make the prop nullable
	RequiredStringEnumWithNull StringEnumWithNull `json:"requiredStringEnumWithNull" mapstructure:"requiredStringEnumWithNull"`
	// RequiredStringEnumWithNullAndNullable: Ref a nullable enum. It should make the prop nullable
	RequiredStringEnumWithNullAndNullable *StringEnumWithNullAndNullable `json:"requiredStringEnumWithNullAndNullable" mapstructure:"requiredStringEnumWithNullAndNullable"`
	// RequiredStringEnumWithNullAndZero: Ref a non nullable enum with zero value.
	RequiredStringEnumWithNullAndZero StringEnumWithNullAndZero `json:"requiredStringEnumWithNullAndZero" mapstructure:"requiredStringEnumWithNullAndZero"`
	// RequiredStringEnumWithZero: Ref a non nullable enum with zero value.
	RequiredStringEnumWithZero StringEnumWithZero `json:"requiredStringEnumWithZero" mapstructure:"requiredStringEnumWithZero"`
	// StringEnum: a regular string enum
	StringEnum StringEnum `json:"stringEnum,omitempty" mapstructure:"stringEnum,omitempty"`
	// StringEnumNullable: a string enum that is nullable
	StringEnumNullable StringEnumNullable `json:"stringEnumNullable,omitempty" mapstructure:"stringEnumNullable,omitempty"`
	// StringEnumWithNull: Ref a non nullable enum. It should not make the prop nullable
	StringEnumWithNull StringEnumWithNull `json:"stringEnumWithNull,omitempty" mapstructure:"stringEnumWithNull,omitempty"`
	// StringEnumWithNullAndNullable: Ref a nullable enum. It should make the prop nullable
	StringEnumWithNullAndNullable *StringEnumWithNullAndNullable `json:"stringEnumWithNullAndNullable,omitempty" mapstructure:"stringEnumWithNullAndNullable,omitempty"`
	// StringEnumWithNullAndZero: Ref a non nullable enum with zero value.
	StringEnumWithNullAndZero StringEnumWithNullAndZero `json:"stringEnumWithNullAndZero,omitempty" mapstructure:"stringEnumWithNullAndZero,omitempty"`
	// StringEnumWithZero: Ref a non nullable enum with zero value.
	StringEnumWithZero StringEnumWithZero `json:"stringEnumWithZero,omitempty" mapstructure:"stringEnumWithZero,omitempty"`
}

// Validate implements basic validation for this model
func (m Wrapper) Validate() error {
	return validation.Errors{
		"nullableStringEnumWithNull": validation.Validate(
			m.NullableStringEnumWithNull, validation.NilOrNotEmpty,
		),
		"nullableStringEnumWithNullAndZero": validation.Validate(
			m.NullableStringEnumWithNullAndZero,
		),
		"nullableStringEnumWithZero": validation.Validate(
			m.NullableStringEnumWithZero,
		),
		"requiredNullableStringEnumWithNull": validation.Validate(
			m.RequiredNullableStringEnumWithNull, validation.NilOrNotEmpty,
		),
		"requiredNullableStringEnumWithNullAndZero": validation.Validate(
			m.RequiredNullableStringEnumWithNullAndZero,
		),
		"requiredNullableStringEnumWithZero": validation.Validate(
			m.RequiredNullableStringEnumWithZero,
		),
		"requiredStringEnum": validation.Validate(
			m.RequiredStringEnum, validation.Required,
		),
		"requiredStringEnumNullable": validation.Validate(
			m.RequiredStringEnumNullable, validation.Required,
		),
		"requiredStringEnumWithNull": validation.Validate(
			m.RequiredStringEnumWithNull, validation.Required,
		),
		"requiredStringEnumWithNullAndNullable": validation.Validate(
			m.RequiredStringEnumWithNullAndNullable, validation.NilOrNotEmpty,
		),
		"requiredStringEnumWithNullAndZero": validation.Validate(
			m.RequiredStringEnumWithNullAndZero,
		),
		"requiredStringEnumWithZero": validation.Validate(
			m.RequiredStringEnumWithZero,
		),
		"stringEnum": validation.Validate(
			m.StringEnum,
		),
		"stringEnumNullable": validation.Validate(
			m.StringEnumNullable,
		),
		"stringEnumWithNull": validation.Validate(
			m.StringEnumWithNull,
		),
		"stringEnumWithNullAndNullable": validation.Validate(
			m.StringEnumWithNullAndNullable, validation.NilOrNotEmpty,
		),
		"stringEnumWithNullAndZero": validation.Validate(
			m.StringEnumWithNullAndZero,
		),
		"stringEnumWithZero": validation.Validate(
			m.StringEnumWithZero,
		),
	}.Filter()
}

// GetNullableStringEnumWithNull returns the NullableStringEnumWithNull property
func (m Wrapper) GetNullableStringEnumWithNull() *StringEnumWithNull {
	return m.NullableStringEnumWithNull
}

// SetNullableStringEnumWithNull sets the NullableStringEnumWithNull property
func (m *Wrapper) SetNullableStringEnumWithNull(val *StringEnumWithNull) {
	m.NullableStringEnumWithNull = val
}

// GetNullableStringEnumWithNullAndZero returns the NullableStringEnumWithNullAndZero property
func (m Wrapper) GetNullableStringEnumWithNullAndZero() *StringEnumWithNullAndZero {
	return m.NullableStringEnumWithNullAndZero
}

// SetNullableStringEnumWithNullAndZero sets the NullableStringEnumWithNullAndZero property
func (m *Wrapper) SetNullableStringEnumWithNullAndZero(val *StringEnumWithNullAndZero) {
	m.NullableStringEnumWithNullAndZero = val
}

// GetNullableStringEnumWithZero returns the NullableStringEnumWithZero property
func (m Wrapper) GetNullableStringEnumWithZero() StringEnumWithZero {
	return m.NullableStringEnumWithZero
}

// SetNullableStringEnumWithZero sets the NullableStringEnumWithZero property
func (m *Wrapper) SetNullableStringEnumWithZero(val StringEnumWithZero) {
	m.NullableStringEnumWithZero = val
}

// GetRequiredNullableStringEnumWithNull returns the RequiredNullableStringEnumWithNull property
func (m Wrapper) GetRequiredNullableStringEnumWithNull() *StringEnumWithNull {
	return m.RequiredNullableStringEnumWithNull
}

// SetRequiredNullableStringEnumWithNull sets the RequiredNullableStringEnumWithNull property
func (m *Wrapper) SetRequiredNullableStringEnumWithNull(val *StringEnumWithNull) {
	m.RequiredNullableStringEnumWithNull = val
}

// GetRequiredNullableStringEnumWithNullAndZero returns the RequiredNullableStringEnumWithNullAndZero property
func (m Wrapper) GetRequiredNullableStringEnumWithNullAndZero() *StringEnumWithNullAndZero {
	return m.RequiredNullableStringEnumWithNullAndZero
}

// SetRequiredNullableStringEnumWithNullAndZero sets the RequiredNullableStringEnumWithNullAndZero property
func (m *Wrapper) SetRequiredNullableStringEnumWithNullAndZero(val *StringEnumWithNullAndZero) {
	m.RequiredNullableStringEnumWithNullAndZero = val
}

// GetRequiredNullableStringEnumWithZero returns the RequiredNullableStringEnumWithZero property
func (m Wrapper) GetRequiredNullableStringEnumWithZero() StringEnumWithZero {
	return m.RequiredNullableStringEnumWithZero
}

// SetRequiredNullableStringEnumWithZero sets the RequiredNullableStringEnumWithZero property
func (m *Wrapper) SetRequiredNullableStringEnumWithZero(val StringEnumWithZero) {
	m.RequiredNullableStringEnumWithZero = val
}

// GetRequiredStringEnum returns the RequiredStringEnum property
func (m Wrapper) GetRequiredStringEnum() StringEnum {
	return m.RequiredStringEnum
}

// SetRequiredStringEnum sets the RequiredStringEnum property
func (m *Wrapper) SetRequiredStringEnum(val StringEnum) {
	m.RequiredStringEnum = val
}

// GetRequiredStringEnumNullable returns the RequiredStringEnumNullable property
func (m Wrapper) GetRequiredStringEnumNullable() StringEnumNullable {
	return m.RequiredStringEnumNullable
}

// SetRequiredStringEnumNullable sets the RequiredStringEnumNullable property
func (m *Wrapper) SetRequiredStringEnumNullable(val StringEnumNullable) {
	m.RequiredStringEnumNullable = val
}

// GetRequiredStringEnumWithNull returns the RequiredStringEnumWithNull property
func (m Wrapper) GetRequiredStringEnumWithNull() StringEnumWithNull {
	return m.RequiredStringEnumWithNull
}

// SetRequiredStringEnumWithNull sets the RequiredStringEnumWithNull property
func (m *Wrapper) SetRequiredStringEnumWithNull(val StringEnumWithNull) {
	m.RequiredStringEnumWithNull = val
}

// GetRequiredStringEnumWithNullAndNullable returns the RequiredStringEnumWithNullAndNullable property
func (m Wrapper) GetRequiredStringEnumWithNullAndNullable() *StringEnumWithNullAndNullable {
	return m.RequiredStringEnumWithNullAndNullable
}

// SetRequiredStringEnumWithNullAndNullable sets the RequiredStringEnumWithNullAndNullable property
func (m *Wrapper) SetRequiredStringEnumWithNullAndNullable(val *StringEnumWithNullAndNullable) {
	m.RequiredStringEnumWithNullAndNullable = val
}

// GetRequiredStringEnumWithNullAndZero returns the RequiredStringEnumWithNullAndZero property
func (m Wrapper) GetRequiredStringEnumWithNullAndZero() StringEnumWithNullAndZero {
	return m.RequiredStringEnumWithNullAndZero
}

// SetRequiredStringEnumWithNullAndZero sets the RequiredStringEnumWithNullAndZero property
func (m *Wrapper) SetRequiredStringEnumWithNullAndZero(val StringEnumWithNullAndZero) {
	m.RequiredStringEnumWithNullAndZero = val
}

// GetRequiredStringEnumWithZero returns the RequiredStringEnumWithZero property
func (m Wrapper) GetRequiredStringEnumWithZero() StringEnumWithZero {
	return m.RequiredStringEnumWithZero
}

// SetRequiredStringEnumWithZero sets the RequiredStringEnumWithZero property
func (m *Wrapper) SetRequiredStringEnumWithZero(val StringEnumWithZero) {
	m.RequiredStringEnumWithZero = val
}

// GetStringEnum returns the StringEnum property
func (m Wrapper) GetStringEnum() StringEnum {
	return m.StringEnum
}

// SetStringEnum sets the StringEnum property
func (m *Wrapper) SetStringEnum(val StringEnum) {
	m.StringEnum = val
}

// GetStringEnumNullable returns the StringEnumNullable property
func (m Wrapper) GetStringEnumNullable() StringEnumNullable {
	return m.StringEnumNullable
}

// SetStringEnumNullable sets the StringEnumNullable property
func (m *Wrapper) SetStringEnumNullable(val StringEnumNullable) {
	m.StringEnumNullable = val
}

// GetStringEnumWithNull returns the StringEnumWithNull property
func (m Wrapper) GetStringEnumWithNull() StringEnumWithNull {
	return m.StringEnumWithNull
}

// SetStringEnumWithNull sets the StringEnumWithNull property
func (m *Wrapper) SetStringEnumWithNull(val StringEnumWithNull) {
	m.StringEnumWithNull = val
}

// GetStringEnumWithNullAndNullable returns the StringEnumWithNullAndNullable property
func (m Wrapper) GetStringEnumWithNullAndNullable() *StringEnumWithNullAndNullable {
	return m.StringEnumWithNullAndNullable
}

// SetStringEnumWithNullAndNullable sets the StringEnumWithNullAndNullable property
func (m *Wrapper) SetStringEnumWithNullAndNullable(val *StringEnumWithNullAndNullable) {
	m.StringEnumWithNullAndNullable = val
}

// GetStringEnumWithNullAndZero returns the StringEnumWithNullAndZero property
func (m Wrapper) GetStringEnumWithNullAndZero() StringEnumWithNullAndZero {
	return m.StringEnumWithNullAndZero
}

// SetStringEnumWithNullAndZero sets the StringEnumWithNullAndZero property
func (m *Wrapper) SetStringEnumWithNullAndZero(val StringEnumWithNullAndZero) {
	m.StringEnumWithNullAndZero = val
}

// GetStringEnumWithZero returns the StringEnumWithZero property
func (m Wrapper) GetStringEnumWithZero() StringEnumWithZero {
	return m.StringEnumWithZero
}

// SetStringEnumWithZero sets the StringEnumWithZero property
func (m *Wrapper) SetStringEnumWithZero(val StringEnumWithZero) {
	m.StringEnumWithZero = val
}
