// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// IntegerEnumWithNullAndZero is an enum.
type IntegerEnumWithNullAndZero int32

// Validate implements basic validation for this model
func (m IntegerEnumWithNullAndZero) Validate() error {
	return InKnownIntegerEnumWithNullAndZero.Validate(m)
}

var (
	IntegerEnumWithNullAndZero0 IntegerEnumWithNullAndZero = 0
	IntegerEnumWithNullAndZero1 IntegerEnumWithNullAndZero = 1
	IntegerEnumWithNullAndZero2 IntegerEnumWithNullAndZero = 2

	// KnownIntegerEnumWithNullAndZero is the list of valid IntegerEnumWithNullAndZero
	KnownIntegerEnumWithNullAndZero = []IntegerEnumWithNullAndZero{
		IntegerEnumWithNullAndZero0,
		IntegerEnumWithNullAndZero1,
		IntegerEnumWithNullAndZero2,
	}

	// KnownIntegerEnumWithNullAndZeroInt32 is the list of valid IntegerEnumWithNullAndZero as int32
	KnownIntegerEnumWithNullAndZeroInt32 = []int32{
		int32(IntegerEnumWithNullAndZero0),
		int32(IntegerEnumWithNullAndZero1),
		int32(IntegerEnumWithNullAndZero2),
	}

	// InKnownIntegerEnumWithNullAndZero is an ozzo-validator for IntegerEnumWithNullAndZero
	InKnownIntegerEnumWithNullAndZero = validation.In(
		IntegerEnumWithNullAndZero0,
		IntegerEnumWithNullAndZero1,
		IntegerEnumWithNullAndZero2,
	)
)
