// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// StringEnumWithNullAndNullable is an enum.
type StringEnumWithNullAndNullable string

// Validate implements basic validation for this model
func (m StringEnumWithNullAndNullable) Validate() error {
	return InKnownStringEnumWithNullAndNullable.Validate(m)
}

var (
	StringEnumWithNullAndNullableBar StringEnumWithNullAndNullable = "bar"
	StringEnumWithNullAndNullableFoo StringEnumWithNullAndNullable = "foo"

	// KnownStringEnumWithNullAndNullable is the list of valid StringEnumWithNullAndNullable
	KnownStringEnumWithNullAndNullable = []StringEnumWithNullAndNullable{
		StringEnumWithNullAndNullableBar,
		StringEnumWithNullAndNullableFoo,
	}
	// KnownStringEnumWithNullAndNullableString is the list of valid StringEnumWithNullAndNullable as string
	KnownStringEnumWithNullAndNullableString = []string{
		string(StringEnumWithNullAndNullableBar),
		string(StringEnumWithNullAndNullableFoo),
	}

	// InKnownStringEnumWithNullAndNullable is an ozzo-validator for StringEnumWithNullAndNullable
	InKnownStringEnumWithNullAndNullable = validation.In(
		StringEnumWithNullAndNullableBar,
		StringEnumWithNullAndNullableFoo,
	)
)
