// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

// PI is a value type.
type PI float64

// DefaultPI is the default value for PI
var DefaultPI = PI(3.14159265359)

// Validate implements basic validation for this model
func (v PI) Validate() error {
	return nil
}
