// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// PetType is an enum.
type PetType string

// DefaultPetType is the default value for PetType
var DefaultPetType = PetType("dog")

// Validate implements basic validation for this model
func (m PetType) Validate() error {
	return InKnownPetType.Validate(m)
}

var (
	PetTypeBird PetType = "bird"
	PetTypeCat  PetType = "cat"
	PetTypeDog  PetType = "dog"

	// KnownPetType is the list of valid PetType
	KnownPetType = []PetType{
		PetTypeBird,
		PetTypeCat,
		PetTypeDog,
	}

	// KnownPetTypeString is the list of valid PetType as string
	KnownPetTypeString = []string{
		string(PetTypeBird),
		string(PetTypeCat),
		string(PetTypeDog),
	}

	// InKnownPetType is an ozzo-validator for PetType
	InKnownPetType = validation.In(
		PetTypeBird,
		PetTypeCat,
		PetTypeDog,
	)
)
