// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"
	"fmt"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// MapWithRef is an object.
type MapWithRef map[string]Person

// NewMapWithRef instantiates a new MapWithRef with default values overriding them as follows:
// 1. Default values specified in the MapWithRef schema
// 2. Default values specified per MapWithRef property
func NewMapWithRef() MapWithRef {
	m := MapWithRef{}

	type alias MapWithRef
	err := json.Unmarshal([]byte(`{"key1":{"address":{"city":"Springfield","number":123,"state":"IL","street":"123 Main St"},"age":25,"name":"John"},"key2":{"address":{"city":"Springfield","number":123,"state":"IL","street":"123 Main St"},"name":"Jane"}}`), (*alias)(&m))
	if err != nil {
		panic(fmt.Errorf("could not unmarshal default values for MapWithRef: %w", err))
	}

	return m
}

// Validate implements basic validation for this model
func (m MapWithRef) Validate() error {
	errors := validation.Errors{}
	for k, v := range m {
		if err := validation.Validate(v); err != nil {
			errors[k] = err
		}
	}
	return errors.Filter()
}
