// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

// EpsilonDouble is a value type.
type EpsilonDouble float64

// DefaultEpsilonDouble is the default value for EpsilonDouble
var DefaultEpsilonDouble = EpsilonDouble(2.220446049250313e-16)

// Validate implements basic validation for this model
func (v EpsilonDouble) Validate() error {
	return nil
}
