// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// Email is a value type.
type Email string

// DefaultEmail is the default value for Email
var DefaultEmail = Email("no@email.com")

// Validate implements basic validation for this model
func (v Email) Validate() error {
	return validation.Validate(
		string(v), is.EmailFormat,
	)
}
