// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

// String is a value type.
type String string

// DefaultString is the default value for String
var DefaultString = String("a string")

// Validate implements basic validation for this model
func (v String) Validate() error {
	return nil
}
