// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test oneOf discriminator support
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ExternalErrorKind is an enum.
type ExternalErrorKind string

// Validate implements basic validation for this model
func (m ExternalErrorKind) Validate() error {
	return InKnownExternalErrorKind.Validate(m)
}

var (
	ExternalErrorKindExternalError ExternalErrorKind = "ExternalError"

	// KnownExternalErrorKind is the list of valid ExternalErrorKind
	KnownExternalErrorKind = []ExternalErrorKind{
		ExternalErrorKindExternalError,
	}

	// KnownExternalErrorKindString is the list of valid ExternalErrorKind as string
	KnownExternalErrorKindString = []string{
		string(ExternalErrorKindExternalError),
	}

	// InKnownExternalErrorKind is an ozzo-validator for ExternalErrorKind
	InKnownExternalErrorKind = validation.In(
		ExternalErrorKindExternalError,
	)
)
