// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test oneOf discriminator support
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// GenericErrorKind is an enum.
type GenericErrorKind string

// Validate implements basic validation for this model
func (m GenericErrorKind) Validate() error {
	return InKnownGenericErrorKind.Validate(m)
}

var (
	GenericErrorKindGenericError GenericErrorKind = "GenericError"

	// KnownGenericErrorKind is the list of valid GenericErrorKind
	KnownGenericErrorKind = []GenericErrorKind{
		GenericErrorKindGenericError,
	}

	// KnownGenericErrorKindString is the list of valid GenericErrorKind as string
	KnownGenericErrorKindString = []string{
		string(GenericErrorKindGenericError),
	}

	// InKnownGenericErrorKind is an ozzo-validator for GenericErrorKind
	InKnownGenericErrorKind = validation.In(
		GenericErrorKindGenericError,
	)
)
