// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test oneOf discriminator support
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ValidationError is an object. a validation error for a form field
type ValidationError struct {
	// Message: the user friendly validation error message
	Message string `json:"message,omitempty" mapstructure:"message,omitempty"`
	// Name: the field name
	Name string `json:"name,omitempty" mapstructure:"name,omitempty"`
}

// NewValidationError instantiates a new ValidationError with default values overriding them as follows:
// 1. Default values specified in the ValidationError schema
// 2. Default values specified per ValidationError property
func NewValidationError() *ValidationError {
	m := &ValidationError{}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for ValidationError. It set the default values for the ValidationError type
func (m *ValidationError) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewValidationError()

	// Unmarshal using an alias to avoid an infinite loop
	type alias ValidationError
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m ValidationError) Validate() error {
	errors := validation.Errors{}
	return errors.Filter()
}

// GetMessage returns the Message property
func (m ValidationError) GetMessage() string {
	return m.Message
}

// SetMessage sets the Message property
func (m *ValidationError) SetMessage(val string) {
	m.Message = val
}

// GetName returns the Name property
func (m ValidationError) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *ValidationError) SetName(val string) {
	m.Name = val
}
