openapi: 3.0.0
info:
  version: 0.1.0
  title: Test Service
paths:
  "/aEndpoint":
    get:
      summary: Health Check
      description: Returns "ok!" message when the service is running
      x-handler-group: Endpoints
      operationId: ServeAEndpoint
      responses:
        '200':
          description: Successfully listed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestType"

components:
  schemas:
    TestType:
      type: object
      required:
        - aRequiredValue
      properties:
        aString:
          type: string
        aStringWithDescription:
          type: string
          description: this is some documentation
        aInt:
          type: integer
        aNumber:
          type: number
        aUint64:
          type: uint64
        aObject:
          type: object
        aTypedObject:
          $ref: "#/components/schemas/SubType"
        aArray:
          type: array
        aStringArray:
          type: array
          items:
            type: string
        aTypedArray:
          type: array
          items:
            $ref: "#/components/schemas/SubType"
        aEnum:
          $ref: "#/components/schemas/EnumType"
        aPointer:
          type: string
          nullable: true
        aNullableArray:
          type: array
          nullable: true
        aNullableObject:
          type: object
          nullable: true
        aObjectWithAdditionalProperties:
          type: object
          additionalProperties:
            type: string
        aObjectWithAdditionalComplexProperties:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/SubType"
        aOneOf:
          oneof:
            - string
            - integer
        aRequiredValue:
          type: string
        aObjectWithAnAnonymousObjectProperty:
          type: object
          properties:
            anon:
              type: string
        aAllOf:
          allOf:
            - $ref: "#/components/schemas/SubType"
            - type: object
              properties:
                extra:
                  type: string
    SubType:
      type: object
      properties:
        foo:
          type: string

    TopLevelAllOf:
      allOf:
        - $ref: "#/components/schemas/SubType"
        - type: object
          properties:
            extra:
              type: string

    ObjectWithNullableReference:
      type: object
      properties:
        foo:
          nullable: true
          allOf:
            - $ref: "#/components/schemas/SubType"


    EnumType:
      type: string
      enum:
        - a
        - b
        - c
