// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ColumnMetadata is an object. Metadata for single column
type ColumnMetadata struct {
	// Comment: Column description
	Comment string `json:"comment,omitempty" mapstructure:"comment,omitempty"`
	// Name: Column name
	Name string `json:"name" mapstructure:"name"`
	// Type: Type metadata
	Type ColumnTypeMetadata `json:"type" mapstructure:"type"`
}

// NewColumnMetadata instantiates a new ColumnMetadata with default values overriding them as follows:
// 1. Default values specified in the ColumnMetadata schema
// 2. Default values specified per ColumnMetadata property
func NewColumnMetadata() *ColumnMetadata {
	m := &ColumnMetadata{
		Type: *NewColumnTypeMetadata(),
	}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for ColumnMetadata. It set the default values for the ColumnMetadata type
func (m *ColumnMetadata) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewColumnMetadata()

	// Unmarshal using an alias to avoid an infinite loop
	type alias ColumnMetadata
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m ColumnMetadata) Validate() error {
	errors := validation.Errors{
		"type": validation.Validate(
			m.Type,
		),
	}
	return errors.Filter()
}

// GetComment returns the Comment property
func (m ColumnMetadata) GetComment() string {
	return m.Comment
}

// SetComment sets the Comment property
func (m *ColumnMetadata) SetComment(val string) {
	m.Comment = val
}

// GetName returns the Name property
func (m ColumnMetadata) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *ColumnMetadata) SetName(val string) {
	m.Name = val
}

// GetType returns the Type property
func (m ColumnMetadata) GetType() ColumnTypeMetadata {
	return m.Type
}

// SetType sets the Type property
func (m *ColumnMetadata) SetType(val ColumnTypeMetadata) {
	m.Type = val
}
