// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ArtistRightFoot is an enum.
type ArtistRightFoot string

// Validate implements basic validation for this model
func (m ArtistRightFoot) Validate() error {
	return InKnownArtistRightFoot.Validate(m)
}

var (
	ArtistRightFootApple      ArtistRightFoot = "apple"
	ArtistRightFootBanana     ArtistRightFoot = "banana"
	ArtistRightFootKiwi       ArtistRightFoot = "kiwi"
	ArtistRightFootOrange     ArtistRightFoot = "orange"
	ArtistRightFootPizza      ArtistRightFoot = "pizza"
	ArtistRightFootWatermelon ArtistRightFoot = "watermelon"

	// KnownArtistRightFoot is the list of valid ArtistRightFoot
	KnownArtistRightFoot = []ArtistRightFoot{
		ArtistRightFootApple,
		ArtistRightFootBanana,
		ArtistRightFootKiwi,
		ArtistRightFootOrange,
		ArtistRightFootPizza,
		ArtistRightFootWatermelon,
	}

	// KnownArtistRightFootString is the list of valid ArtistRightFoot as string
	KnownArtistRightFootString = []string{
		string(ArtistRightFootApple),
		string(ArtistRightFootBanana),
		string(ArtistRightFootKiwi),
		string(ArtistRightFootOrange),
		string(ArtistRightFootPizza),
		string(ArtistRightFootWatermelon),
	}

	// InKnownArtistRightFoot is an ozzo-validator for ArtistRightFoot
	InKnownArtistRightFoot = validation.In(
		ArtistRightFootApple,
		ArtistRightFootBanana,
		ArtistRightFootKiwi,
		ArtistRightFootOrange,
		ArtistRightFootPizza,
		ArtistRightFootWatermelon,
	)
)
