// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// ConnectionProperties is an object.
type ConnectionProperties map[string]interface{}

// NewConnectionProperties instantiates a new ConnectionProperties with default values overriding them as follows:
// 1. Default values specified in the ConnectionProperties schema
// 2. Default values specified per ConnectionProperties property
func NewConnectionProperties() ConnectionProperties {
	m := ConnectionProperties{}

	return m
}

// Validate implements basic validation for this model
func (m ConnectionProperties) Validate() error {
	errors := validation.Errors{}
	for k, v := range m {
		if err := validation.Validate(v); err != nil {
			errors[k] = err
		}
	}
	return errors.Filter()
}
