// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"
	"fmt"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// EitherIdOrNamespaceNameOneOfIdx0 is an object.
type EitherIdOrNamespaceNameOneOfIdx0 struct {
	// Id:
	Id string `json:"id,omitempty" mapstructure:"id,omitempty"`
}

// NewEitherIdOrNamespaceNameOneOfIdx0 instantiates a new EitherIdOrNamespaceNameOneOfIdx0 with default values overriding them as follows:
// 1. Default values specified in the EitherIdOrNamespaceNameOneOfIdx0 schema
// 2. Default values specified per EitherIdOrNamespaceNameOneOfIdx0 property
func NewEitherIdOrNamespaceNameOneOfIdx0() *EitherIdOrNamespaceNameOneOfIdx0 {
	m := &EitherIdOrNamespaceNameOneOfIdx0{}

	type alias EitherIdOrNamespaceNameOneOfIdx0
	err := json.Unmarshal([]byte(`{"id":"a default id from oneOf"}`), (*alias)(m))
	if err != nil {
		panic(fmt.Errorf("could not unmarshal default values for EitherIdOrNamespaceNameOneOfIdx0: %w", err))
	}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for EitherIdOrNamespaceNameOneOfIdx0. It set the default values for the EitherIdOrNamespaceNameOneOfIdx0 type
func (m *EitherIdOrNamespaceNameOneOfIdx0) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewEitherIdOrNamespaceNameOneOfIdx0()

	// Unmarshal using an alias to avoid an infinite loop
	type alias EitherIdOrNamespaceNameOneOfIdx0
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m EitherIdOrNamespaceNameOneOfIdx0) Validate() error {
	errors := validation.Errors{}
	return errors.Filter()
}

// GetId returns the Id property
func (m EitherIdOrNamespaceNameOneOfIdx0) GetId() string {
	return m.Id
}

// SetId sets the Id property
func (m *EitherIdOrNamespaceNameOneOfIdx0) SetId(val string) {
	m.Id = val
}
