// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Person is an object.
type Person struct {
	// Age:
	Age int32 `json:"age,omitempty" mapstructure:"age,omitempty"`
	// Name:
	Name string `json:"name,omitempty" mapstructure:"name,omitempty"`
}

// NewPerson instantiates a new Person with default values overriding them as follows:
// 1. Default values specified in the Person schema
// 2. Default values specified per Person property
func NewPerson() *Person {
	m := &Person{}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for Person. It set the default values for the Person type
func (m *Person) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewPerson()

	// Unmarshal using an alias to avoid an infinite loop
	type alias Person
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m Person) Validate() error {
	errors := validation.Errors{}
	return errors.Filter()
}

// GetAge returns the Age property
func (m Person) GetAge() int32 {
	return m.Age
}

// SetAge sets the Age property
func (m *Person) SetAge(val int32) {
	m.Age = val
}

// GetName returns the Name property
func (m Person) GetName() string {
	return m.Name
}

// SetName sets the Name property
func (m *Person) SetName(val string) {
	m.Name = val
}
