// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"
	"github.com/mitchellh/mapstructure"
)

// Baz is a oneOf type.
type Baz struct {
	data interface{}
}

// NewBaz creates a new Baz instance with no internal value.
func NewBaz() *Baz {
	return &Baz{}
}

// MarshalJSON implements the json.Marshaller interface
func (m Baz) MarshalJSON() ([]byte, error) {
	return json.Marshal(m.data)
}

// UnmarshalJSON implements the json.Unmarshaller interface
func (m *Baz) UnmarshalJSON(bs []byte) error {
	return json.Unmarshal(bs, &m.data)
}

// FromFoo sets the Baz from a Foo
func (m *Baz) FromFoo(data Foo) {
	m.data = data
}

// FromBar sets the Baz from a Bar
func (m *Baz) FromBar(data Bar) {
	m.data = data
}

// FromPerson sets the Baz from a Person
func (m *Baz) FromPerson(data Person) {
	m.data = data
}

// As converts Baz to a user defined structure.
func (m Baz) As(target interface{}) error {
	return mapstructure.Decode(m.data, target)
}

// AsFoo converts Baz to a Foo
func (m Baz) AsFoo() (result Foo, err error) {
	result = *NewFoo()

	return result, mapstructure.Decode(m.data, &result)
}

// AsBar converts Baz to a Bar
func (m Baz) AsBar() (result Bar, err error) {
	return result, mapstructure.Decode(m.data, &result)
}

// AsPerson converts Baz to a Person
func (m Baz) AsPerson() (result Person, err error) {
	result = *NewPerson()

	return result, mapstructure.Decode(m.data, &result)
}
