// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"regexp"
)

// CronPatternError is the error message returned for pattern validation errors on Cron
var CronPatternError = validation.NewError("validation_Cron_pattern_invalid", "must be a valid cron value")

// cronPattern is the validation regexp for Cron
var cronPattern = regexp.MustCompile(`(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})`)

// Cron is a value type.
type Cron string

// Validate implements basic validation for this model
func (v Cron) Validate() error {
	return validation.Validate(
		string(v), validation.Match(cronPattern).ErrorObject(CronPatternError),
	)
}
