// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"
	"fmt"
	"strings"

	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// ObjectWithAdditionalStrings is an object with additional properties.
type ObjectWithAdditionalStrings struct {
	// Field1:
	Field1 string `json:"field1,omitempty" mapstructure:"field1,omitempty"`
	// AdditionalProperties:
	AdditionalProperties map[string]*string `json:"-"`
}

// NewObjectWithAdditionalStrings instantiates a new ObjectWithAdditionalStrings with default values overriding them as follows:
// 1. Default values specified in the ObjectWithAdditionalStrings schema
// 2. Default values specified per ObjectWithAdditionalStrings property
func NewObjectWithAdditionalStrings() *ObjectWithAdditionalStrings {
	m := &ObjectWithAdditionalStrings{}

	return m
}

// UnmarshalJSON all named properties into ObjectWithAdditionalStrings and the rest into the AdditionalProperties map
func (m *ObjectWithAdditionalStrings) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewObjectWithAdditionalStrings()

	var generic map[string]json.RawMessage
	if err := json.Unmarshal(data, &generic); err != nil {
		return err
	}

	var additionalProperties = make(map[string]*string)
	for k, v := range generic {
		switch k {
		case "field1":
			if err := json.Unmarshal(v, &(m.Field1)); err != nil {
				return err
			}
		default:
			var prop *string
			if err := json.Unmarshal(v, &prop); err != nil {
				return err
			}
			additionalProperties[k] = prop
		}
	}

	if len(additionalProperties) > 0 {
		var zero *string
		for k, v := range additionalProperties {
			if v == zero {
				additionalProperties[k] = new(string)
				*additionalProperties[k] = "value"
			}
		}
		m.AdditionalProperties = additionalProperties
	}
	return nil
}

const ObjectWithAdditionalStringsNamedProperties = "|field1"

// MarshalJSON ObjectWithAdditionalStrings by combining the AdditionalProperties with the named properties in a single JSON object.
// An error will be returned if there are duplicate keys.
func (m ObjectWithAdditionalStrings) MarshalJSON() ([]byte, error) {
	type alias ObjectWithAdditionalStrings
	data, err := json.Marshal(alias(m))
	if err != nil {
		return nil, err
	}

	if len(m.AdditionalProperties) > 0 {
		for k, _ := range m.AdditionalProperties {
			if strings.Contains(ObjectWithAdditionalStringsNamedProperties, k) {
				return nil, fmt.Errorf("named key: %s was found in additionalProperties field", k)
			}
		}
		additionalData, err := json.Marshal(m.AdditionalProperties)
		if err != nil {
			return nil, err
		}

		// merge the two JSON objects, we do it at byte level to avoid re-encoding the JSON
		data = data[:len(data)-1]
		additionalData = additionalData[1:]
		if len(data) > 1 {
			data = append(data, ',')
		}
		data = append(data, additionalData...)
	}

	return data, err
}

// Validate implements basic validation for this model
func (m ObjectWithAdditionalStrings) Validate() error {
	errors := validation.Errors{
		"field1": validation.Validate(
			m.Field1, validation.Length(2, 0),
		),
	}
	for k, v := range m.AdditionalProperties {
		if err := validation.Validate(v, validation.NilOrNotEmpty, validation.Length(2, 0), is.EmailFormat); err != nil {
			errors[k] = err
		}
	}
	return errors.Filter()
}

// GetField1 returns the Field1 property
func (m ObjectWithAdditionalStrings) GetField1() string {
	return m.Field1
}

// SetField1 sets the Field1 property
func (m *ObjectWithAdditionalStrings) SetField1(val string) {
	m.Field1 = val
}

func (m *ObjectWithAdditionalStrings) GetAdditionalProperties() map[string]*string {
	return m.AdditionalProperties
}

func (m *ObjectWithAdditionalStrings) SetAdditionalProperties(val map[string]*string) {
	m.AdditionalProperties = val
}
