// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// FooFoo is an object.
type FooFoo map[string]string

// NewFooFoo instantiates a new FooFoo with default values overriding them as follows:
// 1. Default values specified in the FooFoo schema
// 2. Default values specified per FooFoo property
func NewFooFoo() FooFoo {
	m := FooFoo{}

	return m
}

// Validate implements basic validation for this model
func (m FooFoo) Validate() error {
	errors := validation.Errors{}
	for k, v := range m {
		if err := validation.Validate(v); err != nil {
			errors[k] = err
		}
	}
	return errors.Filter()
}
