// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
	"github.com/go-ozzo/ozzo-validation/v4/is"
)

// Bar is an object.
type Bar map[string]string

// NewBar instantiates a new Bar with default values overriding them as follows:
// 1. Default values specified in the Bar schema
// 2. Default values specified per Bar property
func NewBar() Bar {
	m := Bar{}

	return m
}

// Validate implements basic validation for this model
func (m Bar) Validate() error {
	errors := validation.Errors{}
	for k, v := range m {
		if err := validation.Validate(v, validation.Required, is.EmailFormat); err != nil {
			errors[k] = err
		}
	}
	return errors.Filter()
}
