// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Item is an object.
type Item struct {
	// First:
	First string `json:"first" mapstructure:"first"`
}

// NewItem instantiates a new Item with default values overriding them as follows:
// 1. Default values specified in the Item schema
// 2. Default values specified per Item property
func NewItem() *Item {
	m := &Item{}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for Item. It set the default values for the Item type
func (m *Item) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewItem()

	// Unmarshal using an alias to avoid an infinite loop
	type alias Item
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m Item) Validate() error {
	errors := validation.Errors{}
	return errors.Filter()
}

// GetFirst returns the First property
func (m Item) GetFirst() string {
	return m.First
}

// SetFirst sets the First property
func (m *Item) SetFirst(val string) {
	m.First = val
}
