// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test oneOf discriminator support
//	Version: 0.1.0
package generatortest

import (
	"encoding/json"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// NonEmptyContainer is an object.
type NonEmptyContainer struct {
	// Error:
	Error Error `json:"error" mapstructure:"error"`
}

// NewNonEmptyContainer instantiates a new NonEmptyContainer with default values overriding them as follows:
// 1. Default values specified in the NonEmptyContainer schema
// 2. Default values specified per NonEmptyContainer property
func NewNonEmptyContainer() *NonEmptyContainer {
	m := &NonEmptyContainer{}

	return m
}

// UnmarshalJSON implements the json.Unmarshaler interface for NonEmptyContainer. It set the default values for the NonEmptyContainer type
func (m *NonEmptyContainer) UnmarshalJSON(data []byte) error {
	// Set default values
	*m = *NewNonEmptyContainer()

	// Unmarshal using an alias to avoid an infinite loop
	type alias NonEmptyContainer
	err := json.Unmarshal(data, (*alias)(m))
	if err != nil {
		return err
	}
	return nil
}

// Validate implements basic validation for this model
func (m NonEmptyContainer) Validate() error {
	errors := validation.Errors{
		"error": validation.Validate(
			m.Error, validation.NotNil,
			ErrorNilableRule{},
			validation.Skip,
		),
	}
	return errors.Filter()
}

// GetError returns the Error property
func (m NonEmptyContainer) GetError() Error {
	return m.Error
}

// SetError sets the Error property
func (m *NonEmptyContainer) SetError(val Error) {
	m.Error = val
}
