// Code generated by openapi-generator-go DO NOT EDIT.
//
// Source:
//
//	Title: Test
//	Version: 0.1.0
package generatortest

import (
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Foo is an object.
type Foo struct {
	// ArrayRequiredNullable:
	ArrayRequiredNullable []string `json:"array_required_nullable,omitempty" mapstructure:"array_required_nullable,omitempty"`
	// Enum:
	Enum Enum `json:"enum,omitempty" mapstructure:"enum,omitempty"`
	// EnumNullable:
	EnumNullable *Enum `json:"enum_nullable,omitempty" mapstructure:"enum_nullable,omitempty"`
	// EnumRequired:
	EnumRequired Enum `json:"enum_required" mapstructure:"enum_required"`
	// EnumRequiredNullable:
	EnumRequiredNullable *Enum `json:"enum_required_nullable" mapstructure:"enum_required_nullable"`
	// String:
	String string `json:"string,omitempty" mapstructure:"string,omitempty"`
	// StringNullable:
	StringNullable *string `json:"string_nullable,omitempty" mapstructure:"string_nullable,omitempty"`
	// StringRequired:
	StringRequired string `json:"string_required" mapstructure:"string_required"`
	// StringRequiredNullable:
	StringRequiredNullable *string `json:"string_required_nullable" mapstructure:"string_required_nullable"`
}

// Validate implements basic validation for this model
func (m Foo) Validate() error {
	return validation.Errors{
		"arrayRequiredNullable": validation.Validate(
			m.ArrayRequiredNullable, validation.NilOrNotEmpty, validation.Length(1, 2),
		),
		"enum": validation.Validate(
			m.Enum,
		),
		"enumNullable": validation.Validate(
			m.EnumNullable, validation.NilOrNotEmpty,
		),
		"enumRequired": validation.Validate(
			m.EnumRequired, validation.Required,
		),
		"enumRequiredNullable": validation.Validate(
			m.EnumRequiredNullable, validation.NilOrNotEmpty,
		),
	}.Filter()
}

// GetArrayRequiredNullable returns the ArrayRequiredNullable property
func (m Foo) GetArrayRequiredNullable() []string {
	return m.ArrayRequiredNullable
}

// SetArrayRequiredNullable sets the ArrayRequiredNullable property
func (m *Foo) SetArrayRequiredNullable(val []string) {
	m.ArrayRequiredNullable = val
}

// GetEnum returns the Enum property
func (m Foo) GetEnum() Enum {
	return m.Enum
}

// SetEnum sets the Enum property
func (m *Foo) SetEnum(val Enum) {
	m.Enum = val
}

// GetEnumNullable returns the EnumNullable property
func (m Foo) GetEnumNullable() *Enum {
	return m.EnumNullable
}

// SetEnumNullable sets the EnumNullable property
func (m *Foo) SetEnumNullable(val *Enum) {
	m.EnumNullable = val
}

// GetEnumRequired returns the EnumRequired property
func (m Foo) GetEnumRequired() Enum {
	return m.EnumRequired
}

// SetEnumRequired sets the EnumRequired property
func (m *Foo) SetEnumRequired(val Enum) {
	m.EnumRequired = val
}

// GetEnumRequiredNullable returns the EnumRequiredNullable property
func (m Foo) GetEnumRequiredNullable() *Enum {
	return m.EnumRequiredNullable
}

// SetEnumRequiredNullable sets the EnumRequiredNullable property
func (m *Foo) SetEnumRequiredNullable(val *Enum) {
	m.EnumRequiredNullable = val
}

// GetString returns the String property
func (m Foo) GetString() string {
	return m.String
}

// SetString sets the String property
func (m *Foo) SetString(val string) {
	m.String = val
}

// GetStringNullable returns the StringNullable property
func (m Foo) GetStringNullable() *string {
	return m.StringNullable
}

// SetStringNullable sets the StringNullable property
func (m *Foo) SetStringNullable(val *string) {
	m.StringNullable = val
}

// GetStringRequired returns the StringRequired property
func (m Foo) GetStringRequired() string {
	return m.StringRequired
}

// SetStringRequired sets the StringRequired property
func (m *Foo) SetStringRequired(val string) {
	m.StringRequired = val
}

// GetStringRequiredNullable returns the StringRequiredNullable property
func (m Foo) GetStringRequiredNullable() *string {
	return m.StringRequiredNullable
}

// SetStringRequiredNullable sets the StringRequiredNullable property
func (m *Foo) SetStringRequiredNullable(val *string) {
	m.StringRequiredNullable = val
}
