name: test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      ######
      # lint
      ######
      - name: Format
        run: make fmt

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Test
        run: make test
